const CREATE_GROUP_CHAT = "CREATE_GROUP_CHAT";
const REMOVE_USER_GROUP_CHAT = "REMOVE_USER_GROUP_CHAT";
const UPDATE_GROUP_NAME = "UPDATE_GROUP_NAME";
const ADD_USERS_GROUP = "ADD_USERS_GROUP";
const ADD_USERS_SINGLE = "ADD_USERS_SINGLE";
const LEAVE_GROUP_CHAT = "LEAVE_GROUP_CHAT";
const DELETE_GROUP_CHAT = "DELETE_GROUP_CHAT";

module.exports = {
  CREATE_GROUP_CHAT,
  REMOVE_USER_GROUP_CHAT,
  UPDATE_GROUP_NAME,
  ADD_USERS_GROUP,
  ADD_USERS_SINGLE,
  LEAVE_GROUP_CHAT,
  DELETE_GROUP_CHAT,
};
